### ISSUE TITLE
Tweaks showings some errors after update to 1.1.2 from 1.0.0

### ISSUE THREAD

**Issue by lukaevet** [mt-support/tribe-ext-tec-tweaks#7]
I have noticed that `The Events Calendar` running the latest version 6.8.1 with the latest version of `The Events Calendar Extension: Tweaks` at 1.1.2 are showing some errors after update.

`Fatal error: Uncaught Error: Too few arguments to function TEC\Events\Integrations\Plugins\TEC_Tweaks_Extension\Provider::TEC\Events\Integrations\Plugins\TEC_Tweaks_Extension\{closure}(), 1 passed in /home/customer/www/example.com/public_html/wp-includes/class-wp-hook.php on line 324 and exactly 2 expected
in /home/customer/www/example.com/public_html/wp-content/plugins/the-events-calendar/src/Events/Integrations/Plugins/TEC_Tweaks_Extension/Provider.php on line 47 `

Is this some common issue or is this problem on my side?
